[package]
name = "chsql_native"
version = "0.1.3"
edition = "2021"

[features]
# Keep default empty so `cargo test` doesn't pull in loadable extension mode.
default = ["extension"]

# For running tests with an embedded DuckDB
test-duckdb = ["duckdb/bundled", "duckdb/vtab"]

# For building the loadable extension
extension = [
    "duckdb/vtab-loadable",
    "duckdb/duckdb-loadable-macros",
    "dep:libduckdb-sys",
    "dep:duckdb-loadable-macros"
]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true

[[example]]
# crate-type can't be (at the moment) be overriden for specific targets
# src/wasm_lib.rs forwards to src/lib.rs so that we can change from cdylib
# (that is needed while compiling natively) to staticlib (needed since the
# actual linking will be done via emcc
name = "chsql_native"
path = "src/wasm_lib.rs"
crate-type = ["staticlib"]

[dependencies]
duckdb = { version = "1.3.2", default-features = false }
duckdb-loadable-macros = { version = "0.1.5", optional = true }
libduckdb-sys = { version = "1.3.2", features = ["loadable-extension"], optional = true }
byteorder = "1.4"
serde_derive = "1.0.217"
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread"] }
serde = "1.0.217"
clickhouse-rs = { version = "1.1.0-alpha.1", features = ["tokio_io", "tls"] }
clickhouse = "0.13.3"
chrono = "0.4.39"
openssl = { version = "0.10", features = ["vendored"] }
rust_decimal = "1.36"
bigdecimal = "0.4"

[dev-dependencies]
once_cell = "1.21.3"
testcontainers = { version = "0.25", features = ["blocking"] }
ctor = "0.5"